name: sol-ps-ha

networks:
  hanet: {}

x-environment:
  &default-environment
  username_admin_globalaccesslevel: admin
  username_admin_password: ${ADMIN_PASSWORD:-admin}
  system_scaling_maxconnectioncount: 100
  tls_servercertificate_filepath: /run/secret/tls.crt
  redundancy_enable: "yes"
  redundancy_authentication_presharedkey_key: 'Y0HPJpLGfU2qJJ9ffgXrVQMu2u6qOlEqwXDybzUiCGIqsfOQVRQ0vzMy/NUnBX73pqgCNwLjm94DTtO5CXF+wgxS0xrfRfg8h/DZVGCij/8DKkBBfLgx17XVYtqFAit4KVYYge84U1UBAeVCTaMeFAVA7K4otDddjQRr14/nsgEylRz1XsaDINkYeFGIf/3QfcVw+ZqmPZ/Rz/uHuG5T5qJ4MFWOw9tuMrIL53B9qJf189+U3kyiqWQcBpq9ktIDhczA5QGFkkvqel73N9VvY9NioMVUK2ORUCaATR7VraNrH5WrXhbKUqtkO2xkDLQ3dG9iKto+4+3qETX+tuAlFw=='
  redundancy_group_node_sol-pri_connectvia: sol-pri.solxps.handy
  redundancy_group_node_sol-pri_nodetype: message_routing
  redundancy_group_node_sol-bkp_connectvia: sol-bkp.solxps.handy
  redundancy_group_node_sol-bkp_nodetype: message_routing
  redundancy_group_node_sol-mon_connectvia: sol-mon.solxps.handy
  redundancy_group_node_sol-mon_nodetype: monitoring

x-common:
  &default-common
  image: solace-pubsub-enterprise:10.25.0.200
  shm_size: 1g

services:

  primary-broker:
    << : *default-common
    container_name: sol-pri
    hostname: sol-pri
    ports:
      - "212:2222"
    volumes:
      - storage-group-1:/var/lib/solace
      - ../tls.crt:/run/secret/tls.crt
    environment:
      << : *default-environment
      routername: sol-pri
      configsync_enable: "yes"
      redundancy_matelink_connectvia: sol-bkp.solxps.handy
      redundancy_activestandbyrole: primary
      service_semp_tlsport: 1943
    ulimits:
      core: -1
      nofile:
        soft: 2448
        hard: 1048576
    networks:
      hanet:
        aliases:
        - sol-pri.solxps.handy
        - sol-pri

  backup-broker:
    << : *default-common
    container_name: sol-bkp
    hostname: sol-bkp
    ports:
      - "312:2222"
    volumes:
      - storage-group-2:/var/lib/solace
      - ../tls.crt:/run/secret/tls.crt
    environment:
      << : *default-environment
      routername: sol-bkp
      configsync_enable: "yes"
      redundancy_matelink_connectvia: sol-pri.solxps.handy
      redundancy_activestandbyrole: backup
      service_semp_tlsport: 1943
    ulimits:
      core: -1
      nofile:
        soft: 2448
        hard: 1048576
    networks:
      hanet:
        aliases:
        - sol-bkp.solxps.handy
        - sol-bkp

  monitor-broker:
    << : *default-common
    container_name: sol-mon
    hostname: sol-mon
    ports:
      - "412:2222"
    volumes:
      - storage-group-3:/var/lib/solace
      - ../tls.crt:/run/secret/tls.crt
    environment:
      << : *default-environment
      routername: sol-mon
      nodetype: monitoring
      service_semp_tlsport: 1943
    ulimits:
      core: -1
      nofile:
        soft: 2448
        hard: 8192
    networks:
      hanet:
        aliases:
        - sol-mon.solxps.handy
        - sol-mon

  lb:
    container_name: lb
    image: 'haproxy:latest'
    user: 0:0
    volumes:
      - ./assertLeader.perl:/assertLeader.perl
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
    entrypoint:
      - /bin/bash
      - "-c"
      - "perl /assertLeader.perl"
    ports:
      - '48008:8008'
      - '41443:1443'
      - '41943:1943'
      - '41883:1883'
      - '45671:5671'
      - '45672:5672'
      - '48000:8000'
      - '48080:8080'
      - '48443:8443'
      - '48883:8883'
      - '49000:9000'
      - '49443:9443'
      - '45554:55555'
      - '45003:55003'
      - '45443:55443'
      - '41936:1936'
    networks:
      - hanet

volumes:
  storage-group-1:
  storage-group-2:
  storage-group-3: